### PR TITLE
Single IP addresses in Device model specified with standard formats instead of patterns

### LINKED ISSUE #230: Single IPv6 addresses within device
**Problem description**

When redesigning `device`, for IPv4 addresses it was considered just a single IP address, and subnets were only kept for `applicationServer`. But for IPv6 addresses we are keeping the same schema in both device and applicationServer, with same pattern that allows generic masks for subnets, without a clear differentiation.

**Expected behavior**
Behaviour should be consistent for Ipv4 and Ipv6 and only allow IPv6 addresses in device which identify a single device.

We may need to differentiate schemas with dedicated descriptions and maybe patterns. Defining an exact pattern for Ipv6 is complex, so an option would be to remove them from spec and just rely on the RFC 5952 reference. 

As this model is reused by other APIs in other WGs, they may be impacted as well.

### PR DESCRIPTION
**Pull request by jlurien**
#### What type of PR is this?

* enhancement/feature

#### What this PR does / why we need it:

* IPv6 address in device changed to SingleIpv6Adress. IPv6 address in ApplicationServer is not changed
* Patterns for single IPv4 and IPv6 adresses, used in device model, substituted for the standards ipv4 and ipv6 formats defined in JSON-schema

#### Which issue(s) this PR fixes:

Fixes #230 

#### Changelog input

```
* Single IP addresses in Device model specified with standard formats instead of patterns

```

### CODE REVIEW

**Comment by hdamker** [comment]
See my [comment](https://github.com/camaraproject/QualityOnDemand/issues/230#issuecomment-1818992126) within the issue.

**Comment by eric-murray** [comment]
MegaLinter is complaining about trailing spaces again

**Review by eric-murray — APPROVED** [review]

**Review by sfnuser — APPROVED** [review]

**Review by hdamker — APPROVED** [review]
LGTM, thanks @jlurien for the update

**Comment by RandyLevensalor** [comment]
@jlurien @eric-murray I thought that this was just a change to the device and not the application server.

We have use cases for supporting subnets for the application server, including 0.0.0.0/0 for all ipv4 traffic from a specific device and similarly for ipv6.

**Comment by eric-murray** [comment]
> @jlurien @eric-murray I thought that this was just a change to the device and not the application server.
> 
> We have use cases for supporting subnets for the application server, including 0.0.0.0/0 for all ipv4 traffic from a specific device and similarly for ipv6.

The modified application server schema still allows for the specification of subnets, including /0 subnets

**Comment by jlurien** [comment]
I forgot to remark that I have kept the pattern for ApplicationServerIpv4Address. I think that one is quite safe, but as it is the only one with pattern it may appear as inconsistent with the other definitions. I have doubts here.

**Comment by hdamker** [comment]
> I forgot to remark that I have kept the pattern for ApplicationServerIpv4Address. I think that one is quite safe, but as it is the only one with pattern it may appear as inconsistent with the other definitions. I have doubts here.

My vote would go for eliminating the pattern as in `ApplicationServerIpv6Address` and stay with `string` and the description.

BTW: I will finalize the release candidate PR #236 under the assumption that we are closing this PR here. At latest in our call on Friday that should get a go.

**Comment by hdamker** [comment]
> > > I forgot to remark that I have kept the pattern for ApplicationServerIpv4Address. I think that one is quite safe, but as it is the only one with pattern it may appear as inconsistent with the other definitions. I have doubts here.
> > 
> > 
> > My vote would go for eliminating the pattern as in `ApplicationServerIpv6Address` and stay with `string` and the description.
> > BTW: I will finalize the release candidate PR #236 under the assumption that we are closing this PR here. At latest in our call on Friday that should get a go.
> 
> For ApplicationServerIp**v6**Address, pattern is removed. But there is a pattern also in ApplicationServerIp**v4**Address.

My "vote" was for removing the pattern also for ApplicationServerIp**v4**Address. But it don't harm therefore I'm also fine with keeping it, at least for now.

**Comment by hdamker** [comment]
@RandyLevensalor: can you comment/approve if your use case are still covered with the answers above, especially with the [one](https://github.com/camaraproject/QualityOnDemand/pull/237#issuecomment-1830704273) from Eric? If yes we would be good to go here.

**Comment by jlurien** [comment]
> > > > I forgot to remark that I have kept the pattern for ApplicationServerIpv4Address. I think that one is quite safe, but as it is the only one with pattern it may appear as inconsistent with the other definitions. I have doubts here.
> > > 
> > > 
> > > My vote would go for eliminating the pattern as in `ApplicationServerIpv6Address` and stay with `string` and the description.
> > > BTW: I will finalize the release candidate PR #236 under the assumption that we are closing this PR here. At latest in our call on Friday that should get a go.
> > 
> > 
> > For ApplicationServerIp**v6**Address, pattern is removed. But there is a pattern also in ApplicationServerIp**v4**Address.
> 
> My "vote" was for removing the pattern also for ApplicationServerIp**v4**Address. But it don't harm therefore I'm also fine with keeping it, at least for now.

I think this is coherent approach, so implementations do not have to apply different logic per IP address version. I will remove it as well.

**Comment by eric-murray** [comment]
@jlurien
Are you still planning to commit additional changes to remove the pattern for IPv4 addresses?

**Review by hdamker — APPROVED** [review]

**Comment by hdamker** [comment]
Counting also Eric's previous approval in, we are done. I merge now to be able to prepare the RC for our call today.

**Pull request merged**
