### PR TITLE
add 400 - Bad Request for invalid session ID in GET & DELETE /sessions/{sessionId}

### LINKED ISSUE #209: Add 400 - Bad Request for an invalid sessionId GET + DELETE /sessions/{sessionId}:
**Problem description**
When attempting to access a session using the GET /sessions/{sessionId} endpoint, if you provide an invalid UUID as the sessionId parameter, the API will respond with an appropriate HTTP status code to indicate the error. However, it appears that there is currently no specific HTTP status code mentioned in the documentation for this scenario.

**Expected behavior**
The expected behavior for the scenario where an invalid UUID is provided as the sessionId parameter is to return an HTTP status code 400 - Bad Request. This status code signifies that the client's request was malformed or invalid, specifically in the context of an incorrect session ID format.

**Alternative solution**

```yaml
  /sessions/{sessionId}:
    get:
      responses:
         "400":
            $ref: "#/components/responses/Generic400"
```

**Additionally**

Same should be done for DELETE /sessios/{sessionId}

### PR DESCRIPTION
**Pull request by maxl2287**
#### What type of PR is this?

Add one of the following kinds:
* enhancement 

#### What this PR does / why we need it:
There is no expected behaviour for an malformed Session-Id in the GET- & DELETE-request.
This PR shell add a Bad Request (HTTP 400) for the GET & DELETE /sessions/{sessionId} - endpoint.

#### Which issue(s) this PR fixes:

Fixes #209

### CODE REVIEW

**Comment by RandyLevensalor** [comment]
@maxl2287 please rebase.  Your other PR to fix linting has been merged.  I'll provide comments in the ticker per this patch.

**Comment by maxl2287** [comment]
@RandyLevensalor done. 🐈‍⬛

**Comment by maxl2287** [comment]
@RandyLevensalor could you do a review again, please ?

**Review by eric-murray — APPROVED** [review]

**Review by hdamker — APPROVED** [review]
LGTM ... @RandyLevensalor will you merge?

**Review by RandyLevensalor — APPROVED** [review]

**Pull request merged**
