### PR TITLE
Remove unused messages object in SessionInfo schema

### LINKED ISSUE #309: Purpose of `messages` array in SessionInfo schema is undocumented
**Problem description**
`SessionInfo` schema in the spec contains `messages` object. The purpose of this object is undocumented

**Expected behavior**
This array object seems unnecessary and can be removed. If there is an purpose, it needs to be documented for implementation by vendors and use by developers.

### PR DESCRIPTION
**Pull request by sfnuser**
#### What type of PR is this?
* correction
#### What this PR does / why we need it:
* Remove unused `messages` object in the `SessionInfo` schema
#### Which issue(s) this PR fixes:

Fixes #309

#### Special notes for reviewers:
As discussed in today's [call](https://wiki.camaraproject.org/display/CAM/2024-06-28+Quality+on+Demand+-+Meeting+Minutes) 

#### Changelog input

```
Removed unused `messages` object in the `SessionInfo` schema
```

### CODE REVIEW

**Review by RandyLevensalor — APPROVED** [review]
LGTM

**Review by hdamker — APPROVED** [review]
LGTM

**Review by maxl2287 — APPROVED** [review]

**Comment by maxl2287** [comment]
LGTM

**Review by eric-murray — APPROVED** [review]

**Comment by maxl2287** [comment]
@hdamker I guess we can merge. I do not expect now any turn-around.

**Pull request merged**
