### PR TITLE
Add QoS Profile User Story

### LINKED ISSUE #341: Add user story for QoS Profile
**Problem description**
Create a user story for the QoS profile

**Expected action**
A user story using the following template. https://github.com/camaraproject/Commonalities/blob/main/documentation/Userstory-template.md

**Additional context**

### PR DESCRIPTION
**Pull request by benhepworth**
#### What type of PR is this?

Add one of the following kinds:
* documentation

#### What this PR does / why we need it:

Add Qos Profile User Story. Required for full release.

#### Which issue(s) this PR fixes:

Fixes #341 

#### Special notes for reviewers:

Made a few formatting and text changes that are different than the QoD user story (i.e. some extra spacing to make it more readable). Should we update the QoD User Story also to align?

#### Changelog input

```
Added User Story for QoS Profile.
```

#### Additional documentation 

This section can be blank.

```
docs

```

### CODE REVIEW

**Review by RandyLevensalor — APPROVED** [review]
I approve.  Since I helped with it, others need to chime in as well :)

**Comment by hdamker** [comment]
@benhepworth within the last QoD call we discussed some changes, if I remember in the section "Activities/Steps", which you agreed to make. Do you still plan to add them?

Beyond that the PR LGTM. Would be good to start here the final review asap.

**Comment by benhepworth** [comment]
@hdamker - yes, I added those changes on Friday and updated the PR. The changes specifically were:

- use Consumer:Developer instead of Customer:Developer throughout
- under Ends with, change `user` to `Consumer:Developer`

From my notes those were all the needed changes - was there anything else that needs updating? I think we can move this to final review now.

**Review by hdamker — APPROVED** [review]
LGTM (@benhepworth had overseen the commit from Friday)

**Review by eric-murray — APPROVED** [review]

**Review by RandyLevensalor — APPROVED** [review]

**Pull request merged**
