### PR TITLE
Clean up of directories according to issue #49

### PR DESCRIPTION
**Pull request by hdamker**
Clean up according to #49:

- Moved all presentation files into documentation/SupportingDocuments/Presentations
- Deleted obsolete README.md files

### CODE REVIEW

**Comment by shilpa-padgaonkar** [comment]
For images used in https://github.com/camaraproject/QualityOnDemand/tree/main/documentation/API_documentation/ there is a directory named resources in QoD. In commonalities, the directory is named images https://github.com/camaraproject/WorkingGroups/tree/main/Commonalities/documentation/images

Do we want to keep the same naming?

**Comment by shilpa-padgaonkar** [comment]
May be you want to place the documentation for eg https://github.com/hdamker/QualityOnDemand/blob/clean-up-patch2-%2349/code/API_definitions/Notifications.md and https://github.com/hdamker/QualityOnDemand/blob/clean-up-patch2-%2349/code/API_definitions/QoSProfile_Mapping_Table.md in the api documentation folder?

**Comment by hdamker** [comment]
> Do we want to follow the same naming convention?

If all sub projects agree on it, sure. But covered by the current issue.

**Comment by hdamker** [comment]
> May be you want to place the documentation for eg https://github.com/hdamker/QualityOnDemand/blob/clean-up-patch2-%2349/code/API_definitions/Notifications.md and https://github.com/hdamker/QualityOnDemand/blob/clean-up-patch2-%2349/code/API_definitions/QoSProfile_Mapping_Table.md and https://github.com/hdamker/QualityOnDemand/blob/clean-up-patch2-%2349/documentation/QoD-API-Readiness-Checklist.md in the api documentation folder?

Moved Notifications.md and QoD-API-Readiness-Checklist.md into API_documentation folder. Kept QoSProfile_Mapping_Table.md within its location as it is linked within YAML files and changed in #43.

**Comment by hdamker** [comment]
> What about [camaraproject/WorkingGroups#63 (comment)](https://github.com/camaraproject/WorkingGroups/issues/63#issuecomment-1259452546) ?

@shilpa-padgaonkar I created a new issue for that #52

**Pull request merged**
